[package]
name = "web_crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.33", features = ["full"] }
reqwest = { version = "0.12.12", features = ["json"] }
rusqlite = "0.34.0"
csv = "1.2"
scraper = "0.23.1"
url = "2.3"
structopt = "0.3"

[features]
default = []
